KaishiKakomonDojo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('kakomon.urls')),
    path('api/', include('api.urls')),
    path('admin/', admin.site.urls),
]

api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from .views import *


# view set の場合は simple/Default Routerを使う

app_name = 'api'

urlpatterns = [
    # ex: /api/courses/
    path('courses/', CoursesViewIndex.as_view(), name='courses_index'),

    # ex: /api/courses/1/
    path('courses/<int:pk>/', CoursesViewDetail.as_view(), name='courses_detail'),

    # ex: /api/issues/
    path('issues/', IssuesViewIndex.as_view(), name='issues_index'),

    # ex: /api/issues/1/
    path('issues/<int:pk>', IssuesViewDetail.as_view(), name='issues_detail'),
]

kakomon/urls.py
from django.urls import path

from . import views

app_name = 'courses'
urlpatterns = [
    # ex: /
    path('', views.index, name='index'),

    # ex: /courses/1/
    path('courses/<int:course_id>/', views.detail, name='detail'),

    # ex: /courses/1/
    path('courses/<int:course_id>/create/', views.create, name='create'),

]

api/models.py
from django.db import models

# Create your models here.

kakomon/models.py
import re

from django.db import models


class Course(models.Model):
    course_name = models.CharField(max_length=50)
    course_code = models.CharField(max_length=10, null=True)
    academic_year = models.IntegerField('開講年度')
    semester = models.CharField('学期', max_length=4)
    credits = models.IntegerField('単位数')

    def __str__(self):
        return self.course_name

    def is_hands_on(self):
        return bool(re.fullmatch(r'.*実習.*', self.course_name))


class Issue(models.Model):
    title = models.TextField()
    content = models.TextField()
    lecture_number = models.IntegerField()
    course = models.ForeignKey(Course,
                                  on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class SampleAnswer(models.Model):
    issue = models.ForeignKey(Issue,
                                 on_delete=models.CASCADE)
    text = models.TextField()
    image = models.ImageField()

    def __str__(self):
        return self.text

api/views.py
from rest_framework import generics

from .serializers import *
from kakomon.models import Course, Issue, SampleAnswer


# ListAPIView : GET 全件取得
class CoursesViewIndex(generics.ListAPIView):
    queryset = Course.objects.all()
    serializer_class = CourseSerializer


# RetrieveAPIView : GET 一件取得
class CoursesViewDetail(generics.RetrieveAPIView):
    queryset = Course.objects.filter()
    serializer_class = CourseSerializer


class IssuesViewIndex(generics.ListAPIView):
    queryset = Issue.objects.all()
    serializer_class = IssueSerializer


class IssuesViewDetail(generics.RetrieveAPIView):
    queryset = Issue.objects.filter()
    serializer_class = IssueSerializer

kakomon/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.template import loader
from django.urls import reverse

from .models import Course


def index(request):
    """
    講義一覧を表示
    """
    courses = Course.objects.order_by('id')
    template = loader.get_template('courses/index.html')
    context = {
        'courses': courses,
    }
    return render(request, 'courses/index.html', context)
    # この記述は以下の記述と同じ
    # return HttpResponse(template.render(context, request))


def detail(request, course_id):

    # try:
    #    course = Course.objects.get(pk=course_id)
    # except Course.DoesNotExist:
    #    raise Http404('講義が存在しません')

    # get_list_or_404() は objects.filter() と同じ
    course = get_object_or_404(Course, pk=course_id)

    return render(request, 'courses/detail.html', {'course': course})
    # return HttpResponse(f'{course_id} の講義情報')


def create(request, course_id):
    course = get_object_or_404(Course, pk=course_id)
    try:
        created_issue = course.issue_set.create(
            title=request.POST['title'],
            content=request.POST['content'],
            lecture_number=request.POST['lecture_number'],
        )
        print(created_issue)
    except KeyError:
        return render(request, 'courses/detail.html',
                      {'course': course,
                       'error_message': '誤ったデータです'})
    else:
        return HttpResponseRedirect(reverse('courses:detail', args=(course.id, )))

kakomon/templates/courses/detail.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>{{course.course_name}} - 過去問道場</title>

    {% load static %}
    <link rel="stylesheet" href="{% static 'courses/style.css' %}" type="text/css">

</head>
<body>
<h1>{{course.course_name}}</h1>
<p style="text-align: end; color: gray;">
{{ course.academic_year }}年生{{ course.semester }}学期 <br />
({{ course.credits }}単位)
</p>

{% for issue in course.issue_set.all %}
<ul id="issues">
        <h2>{{ issue.title }}</h2>
        <p>{{ issue.content }}</p>
</ul>
{% endfor %}

<form action="{% url 'courses:create' course.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ course.course_name }}の課題を新規登録</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>
        {% endif %}


        <label for="title">タイトル</label>
        <input type="text" id="title" name="title">
        <br />
        <label for="content">内容</label>
        <textarea id="content" name="content"></textarea>
        <br />
        <label for="lecture_number">出題回</label>
        <input type="number" id="lecture_number" name="lecture_number">

    </fieldset>
    <button type="submit" value="create">作成する</button>
</form>

<a href="/">講義一覧へ戻る</a>
</body>
</html>

kakomon/templates/courses/index.html
<!doctype html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>情報学部過去問道場 - 開志専門職大学</title>

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'courses/style.css' %}">
</head>
<body>
<h1>過去問道場</h1>
{% if courses %}
<ul>
    {% for course in courses %}
    <li><a href="{% url 'courses:detail' course.id %}">
        {{ course.course_name }}</a></li>
    {% endfor %}
</ul>
{% else %}
<p>利用できるコースがありません。</p>
{% endif %}
</body>
</html>